spring:
  application:
    name: bancada-os-api
  datasource:
    url: jdbc:postgresql://localhost:5432/bancada_db
    username: bancada_os
    password: bancada
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect